import { CollectibleType } from "isaac-typescript-definitions";
import { ReadonlySet } from "isaacscript-common";

export const ANGEL_ROOM_COLLECTIBLES = new ReadonlySet<CollectibleType>([
  CollectibleType.BLOOD_OF_THE_MARTYR, // 7
  CollectibleType.BIBLE, // 33
  CollectibleType.ROSARY, // 72
  CollectibleType.BOOK_OF_REVELATIONS, // 78
  CollectibleType.RELIC, // 98
  CollectibleType.HALO, // 101
  CollectibleType.WAFER, // 108
  CollectibleType.GUARDIAN_ANGEL, // 112
  CollectibleType.DEAD_SEA_SCROLLS, // 124
  CollectibleType.STIGMATA, // 138
  CollectibleType.SCAPULAR, // 142
  CollectibleType.PRAYER_CARD, // 146
  CollectibleType.HABIT, // 156
  CollectibleType.CELTIC_CROSS, // 162
  CollectibleType.MITRE, // 173
  CollectibleType.HOLY_WATER, // 178
  CollectibleType.SACRED_HEART, // 182
  CollectibleType.HOLY_GRAIL, // 184
  CollectibleType.DEAD_DOVE, // 185
  CollectibleType.JESUS_JUICE, // 197
  CollectibleType.TRINITY_SHIELD, // 243
  CollectibleType.HOLY_MANTLE, // 313
  CollectibleType.BREATH_OF_LIFE, // 326
  CollectibleType.GODHEAD, // 331
  CollectibleType.LAZARUS_RAGS, // 332
  CollectibleType.MIND, // 333
  CollectibleType.BODY, // 334
  CollectibleType.SOUL, // 335
  CollectibleType.SWORN_PROTECTOR, // 363
  CollectibleType.HOLY_LIGHT, // 374
  CollectibleType.CENSER, // 387
  CollectibleType.SERAPHIM, // 390
  CollectibleType.SPEAR_OF_DESTINY, // 400
  CollectibleType.PURITY, // 407
  CollectibleType.IMMACULATE_CONCEPTION, // 413
  CollectibleType.CROWN_OF_LIGHT, // 415
  CollectibleType.CIRCLE_OF_PROTECTION, // 423
  CollectibleType.GLYPH_OF_BALANCE, // 464
  CollectibleType.VOID, // 477
  CollectibleType.EDENS_SOUL, // 490
  CollectibleType.DUALITY, // 498
  CollectibleType.LIL_DELIRIUM, // 519
  CollectibleType.SEVEN_SEALS, // 526
  CollectibleType.ANGELIC_PRISM, // 528
  CollectibleType.TRISAGION, // 533
  CollectibleType.HALLOWED_GROUND, // 543
  CollectibleType.PASCHAL_CANDLE, // 567
  CollectibleType.DIVINE_INTERVENTION, // 568
  CollectibleType.IMMACULATE_HEART, // 573
  CollectibleType.MONSTRANCE, // 574
  CollectibleType.SPIRIT_SWORD, // 579
  CollectibleType.BOOK_OF_VIRTUES, // 584
  CollectibleType.STAIRWAY, // 586
  CollectibleType.ACT_OF_CONTRITION, // 601
  CollectibleType.GENESIS, // 622
  CollectibleType.PURGATORY, // 634
  CollectibleType.URN_OF_SOULS, // 640
  CollectibleType.REVELATION, // 643
  CollectibleType.STAR_OF_BETHLEHEM, // 651
  CollectibleType.VADE_RETRO, // 653
  CollectibleType.JAR_OF_WISPS, // 685
  CollectibleType.SOUL_LOCKET, // 686
  CollectibleType.SACRED_ORB, // 691
  CollectibleType.SALVATION, // 696
]);
