export enum CharacterObjectiveKind {
  MOM,
  IT_LIVES,
  ISAAC,
  BLUE_BABY,
  SATAN,
  LAMB,

  MEGA_SATAN,
  BOSS_RUSH,
  HUSH,
  DELIRIUM,
  MOTHER,
  BEAST,
  ULTRA_GREED,

  NO_HIT_BASEMENT_1,
  NO_HIT_BASEMENT_2,
  NO_HIT_CAVES_1,
  NO_HIT_CAVES_2,
  NO_HIT_DEPTHS_1,
  NO_HIT_DEPTHS_2,
  NO_HIT_WOMB_1,
  NO_HIT_WOMB_2,
  NO_HIT_SHEOL_CATHEDRAL,
  NO_HIT_DARK_ROOM_CHEST,
  NO_HIT_DOWNPOUR_1,
  NO_HIT_DOWNPOUR_2,
  NO_HIT_MINES_1,
  NO_HIT_MINES_2,
  NO_HIT_MAUSOLEUM_1,
  NO_HIT_MAUSOLEUM_2,
  NO_HIT_CORPSE_1,
  NO_HIT_CORPSE_2,
}

const CHARACTER_OBJECTIVE_KIND_NAMES = {
  [CharacterObjectiveKind.MOM]: "Mom",
  [CharacterObjectiveKind.IT_LIVES]: "It Lives",
  [CharacterObjectiveKind.ISAAC]: "Isaac",
  [CharacterObjectiveKind.BLUE_BABY]: "Blue Baby",
  [CharacterObjectiveKind.SATAN]: "Satan",
  [CharacterObjectiveKind.LAMB]: "The Lamb",
  [CharacterObjectiveKind.MEGA_SATAN]: "Mega Satan",
  [CharacterObjectiveKind.BOSS_RUSH]: "Boss Rush",
  [CharacterObjectiveKind.HUSH]: "Hush",
  [CharacterObjectiveKind.DELIRIUM]: "Delirium",
  [CharacterObjectiveKind.MOTHER]: "Mother",
  [CharacterObjectiveKind.BEAST]: "The Beast",
  [CharacterObjectiveKind.ULTRA_GREED]: "Ultra Greed",
  [CharacterObjectiveKind.NO_HIT_BASEMENT_1]: "1",
  [CharacterObjectiveKind.NO_HIT_BASEMENT_2]: "2",
  [CharacterObjectiveKind.NO_HIT_CAVES_1]: "3",
  [CharacterObjectiveKind.NO_HIT_CAVES_2]: "4",
  [CharacterObjectiveKind.NO_HIT_DEPTHS_1]: "5",
  [CharacterObjectiveKind.NO_HIT_DEPTHS_2]: "6",
  [CharacterObjectiveKind.NO_HIT_WOMB_1]: "7",
  [CharacterObjectiveKind.NO_HIT_WOMB_2]: "8",
  [CharacterObjectiveKind.NO_HIT_SHEOL_CATHEDRAL]: "10",
  [CharacterObjectiveKind.NO_HIT_DARK_ROOM_CHEST]: "11",
  [CharacterObjectiveKind.NO_HIT_DOWNPOUR_1]: "1 (alt)",
  [CharacterObjectiveKind.NO_HIT_DOWNPOUR_2]: "2 (alt)",
  [CharacterObjectiveKind.NO_HIT_MINES_1]: "3 (alt)",
  [CharacterObjectiveKind.NO_HIT_MINES_2]: "4 (alt)",
  [CharacterObjectiveKind.NO_HIT_MAUSOLEUM_1]: "5 (alt)",
  [CharacterObjectiveKind.NO_HIT_MAUSOLEUM_2]: "6 (alt)",
  [CharacterObjectiveKind.NO_HIT_CORPSE_1]: "7 (alt)",
  [CharacterObjectiveKind.NO_HIT_CORPSE_2]: "8 (alt)",
} as const satisfies Record<CharacterObjectiveKind, string>;

export function getCharacterObjectiveKindName(
  kind: CharacterObjectiveKind,
): string {
  return CHARACTER_OBJECTIVE_KIND_NAMES[kind];
}
