import { CardType } from "isaac-typescript-definitions";

const DEFAULT_CARD_QUALITY = 0;

export const CARD_QUALITIES = {
  [CardType.NULL]: DEFAULT_CARD_QUALITY, // 0
  [CardType.FOOL]: 1, // 1
  [CardType.MAGICIAN]: 3, // 2
  [CardType.HIGH_PRIESTESS]: 2, // 3
  [CardType.EMPRESS]: 2, // 4
  [CardType.EMPEROR]: 1, // 5
  [CardType.HIEROPHANT]: 3, // 6
  [CardType.LOVERS]: 1, // 7
  [CardType.CHARIOT]: 1, // 8
  [CardType.JUSTICE]: 1, // 9
  [CardType.HERMIT]: 1, // 10
  [CardType.WHEEL_OF_FORTUNE]: 1, // 11
  [CardType.STRENGTH]: 3, // 12
  [CardType.HANGED_MAN]: 1, // 13
  [CardType.DEATH]: 2, // 14
  [CardType.TEMPERANCE]: 2, // 15
  [CardType.DEVIL]: 2, // 16
  [CardType.TOWER]: 2, // 17
  [CardType.STARS]: 1, // 18
  [CardType.MOON]: 1, // 19
  [CardType.SUN]: 3, // 20
  [CardType.JUDGEMENT]: 2, // 21
  [CardType.WORLD]: 1, // 22
  [CardType.TWO_OF_CLUBS]: 2, // 23
  [CardType.TWO_OF_DIAMONDS]: 3, // 24
  [CardType.TWO_OF_SPADES]: 2, // 25
  [CardType.TWO_OF_HEARTS]: 1, // 26
  [CardType.ACE_OF_CLUBS]: 3, // 27
  [CardType.ACE_OF_DIAMONDS]: 3, // 28
  [CardType.ACE_OF_SPADES]: 3, // 29
  [CardType.ACE_OF_HEARTS]: 3, // 30
  [CardType.JOKER]: 4, // 31
  [CardType.RUNE_HAGALAZ]: 0, // 32
  [CardType.RUNE_JERA]: 3, // 33
  [CardType.RUNE_EHWAZ]: 3, // 34
  [CardType.RUNE_DAGAZ]: 3, // 35
  [CardType.RUNE_ANSUZ]: 1, // 36
  [CardType.RUNE_PERTHRO]: 4, // 37
  [CardType.RUNE_BERKANO]: 1, // 38
  [CardType.RUNE_ALGIZ]: 4, // 39
  [CardType.RUNE_BLANK]: 2, // 40
  [CardType.RUNE_BLACK]: 3, // 41
  [CardType.CHAOS]: 4, // 42
  [CardType.CREDIT]: 4, // 43
  [CardType.RULES]: 0, // 44
  [CardType.AGAINST_HUMANITY]: 3, // 45
  [CardType.SUICIDE_KING]: 0, // 46
  [CardType.GET_OUT_OF_JAIL_FREE]: 2, // 47
  [CardType.QUESTION_MARK]: 3, // 48
  [CardType.DICE_SHARD]: 4, // 49
  [CardType.EMERGENCY_CONTACT]: 1, // 50
  [CardType.HOLY]: 3, // 51
  [CardType.HUGE_GROWTH]: 3, // 52
  [CardType.ANCIENT_RECALL]: 3, // 53
  [CardType.ERA_WALK]: 2, // 54
  [CardType.RUNE_SHARD]: 0, // 55
  [CardType.REVERSE_FOOL]: 1, // 56
  [CardType.REVERSE_MAGICIAN]: 2, // 57
  [CardType.REVERSE_HIGH_PRIESTESS]: 0, // 58
  [CardType.REVERSE_EMPRESS]: 3, // 59
  [CardType.REVERSE_EMPEROR]: 1, // 60
  [CardType.REVERSE_HIEROPHANT]: 4, // 61
  [CardType.REVERSE_LOVERS]: 4, // 62
  [CardType.REVERSE_CHARIOT]: 2, // 63
  [CardType.REVERSE_JUSTICE]: 2, // 64
  [CardType.REVERSE_HERMIT]: 2, // 65
  [CardType.REVERSE_WHEEL_OF_FORTUNE]: 0, // 66
  [CardType.REVERSE_STRENGTH]: 3, // 67
  [CardType.REVERSE_HANGED_MAN]: 2, // 68
  [CardType.REVERSE_DEATH]: 1, // 69
  [CardType.REVERSE_TEMPERANCE]: 1, // 70
  [CardType.REVERSE_DEVIL]: 2, // 71
  [CardType.REVERSE_TOWER]: 3, // 72
  [CardType.REVERSE_STARS]: 4, // 73
  [CardType.REVERSE_MOON]: 3, // 74
  [CardType.REVERSE_SUN]: 3, // 75
  [CardType.REVERSE_JUDGEMENT]: 4, // 76
  [CardType.REVERSE_WORLD]: 3, // 77
  [CardType.CRACKED_KEY]: 2, // 78
  [CardType.QUEEN_OF_HEARTS]: 2, // 79
  [CardType.WILD]: 3, // 80
  [CardType.SOUL_OF_ISAAC]: 4, // 81
  [CardType.SOUL_OF_MAGDALENE]: 1, // 82
  [CardType.SOUL_OF_CAIN]: 3, // 83
  [CardType.SOUL_OF_JUDAS]: 0, // 84
  [CardType.SOUL_OF_BLUE_BABY]: 1, // 85
  [CardType.SOUL_OF_EVE]: 2, // 86
  [CardType.SOUL_OF_SAMSON]: 3, // 87
  [CardType.SOUL_OF_AZAZEL]: 3, // 88
  [CardType.SOUL_OF_LAZARUS]: 2, // 89
  [CardType.SOUL_OF_EDEN]: 4, // 90
  [CardType.SOUL_OF_LOST]: 3, // 91
  [CardType.SOUL_OF_LILITH]: 3, // 92
  [CardType.SOUL_OF_KEEPER]: 2, // 93
  [CardType.SOUL_OF_APOLLYON]: 2, // 94
  [CardType.SOUL_OF_FORGOTTEN]: 2, // 95
  [CardType.SOUL_OF_BETHANY]: 0, // 96
  [CardType.SOUL_OF_JACOB_AND_ESAU]: 2, // 97
} as const satisfies Record<CardType, Quality>;
